/**
 * 회고 작성 페이지
 */

import { useState, useEffect, useCallback, useRef, useMemo } from 'react';
import type { FC } from 'react';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { useCreateRetrospective, useRetrospective, useUpdateRetrospective } from '../../../hooks/api/useRetrospective';
import { useTemplateSummaries, useRenderTemplate, useTemplates } from '../../../hooks/api/useTemplate';
import { useProblemDetail } from '../../../hooks/api/useProblem';
import { RetrospectiveEditor } from '../components/RetrospectiveEditor';
import { Spinner } from '../../../components/ui/Spinner';
import { Layout } from '../../../components/layout/Layout';
import { Button } from '../../../components/ui/Button';
import { formatTierFromDifficulty, getTierColor } from '../../../utils/tier';
import { LanguageBadge } from '../../../components/common/LanguageBadge';
import { toast } from 'sonner';
import { getErrorMessage, isApiError } from '../../../types/api/common.types';
import { useOnboardingStore } from '../../../stores/onboarding.store';
import { Copy, ChevronLeft } from 'lucide-react';
import type { ProblemResult, RetrospectiveRequest } from '../../../types/api/retrospective.types';
import { AiReviewCard } from '../../../components/retrospective/AiReviewCard';
import type { TemplateSummary } from '../../../types/api/template.types';
import { buildRepresentativeCategoriesFromSource } from '../../../utils/problemCategory';
import { getCategoryLabel } from '../../../utils/constants';

/**
 * 제목 초기값 포맷 상수
 * 성공: 해결 회고, 실패: 미해결 회고
 */
const DEFAULT_TITLE_FORMAT = '# 🏆 [백준/BOJ] {{problemId}}번 {{problemTitle}} ({{language}}) {{result}} 회고';

/**
 * 제목 포맷의 플레이스홀더를 실제 값으로 치환
 */
const formatTitle = (format: string, params: {
    problemId: string;
    problemTitle: string;
    language: string;
    result: string;
}): string => {
    return format
        .replace(/\{\{problemId\}\}/g, params.problemId)
        .replace(/\{\{problemTitle\}\}/g, params.problemTitle)
        .replace(/\{\{language\}\}/g, params.language)
        .replace(/\{\{result\}\}/g, params.result);
};

type TemplateFallbackInfo = {
    reason: string | null;
};

const getTemplateFallbackMessage = (reason: string | null): string => {
    if (reason === 'TEMPLATE_RENDER_TIMEOUT') {
        return '템플릿 렌더링 시간이 초과되어 기본 템플릿으로 대체되었습니다.';
    }
    return '템플릿 렌더링 중 일부 문제가 발생해 기본 템플릿으로 대체되었습니다.';
};

/**
 * 중복된 "제출한 코드" 섹션 제거 및 정리
 */
const removeDuplicateCodeSections = (content: string): string => {
    // 모든 "## 제출한 코드" 섹션 찾기 (더 정확한 패턴)
    // 섹션 헤더부터 다음 섹션 헤더나 구분선, 문서 끝까지 매칭
    const codeSectionPattern = /(##\s*제출한\s*코드(?:\s*\n|[\s\S]*?)(?:```[\s\S]*?```|(?=\n##|\n---|$)))/gi;
    const matches: RegExpMatchArray[] = [];
    let match: RegExpMatchArray | null;
    
    // 모든 매칭 결과 수집
    while ((match = codeSectionPattern.exec(content)) !== null) {
        matches.push(match);
    }
    
    if (matches.length <= 1) {
        return content; // 중복이 없으면 그대로 반환
    }
    
    // 마지막 "## 제출한 코드" 섹션만 유지
    // 모든 섹션을 역순으로 제거 (뒤에서부터 제거하여 인덱스 문제 방지)
    let cleaned = content;
    for (let i = matches.length - 2; i >= 0; i--) {
        // 마지막 섹션이 아닌 것들만 제거
        const matchText = matches[i][0];
        cleaned = cleaned.replace(matchText, '');
    }
    
    // 중복된 공백 줄 정리
    cleaned = cleaned.replace(/\n{3,}/g, '\n\n').trim();
    
    return cleaned;
};

/**
 * 플레이스홀더를 실제 값으로 치환
 */
const replacePlaceholders = (
    content: string,
    problemId: string,
    tier?: string | null
): string => {
    // 문제 링크 생성
    const problemLink = `https://www.acmicpc.net/problem/${problemId}`;
    
    // 티어 정보 (없으면 "티어 정보 없음")
    const tierText = tier || '티어 정보 없음';
    
    // 플레이스홀더 치환
    return content
        .replace(/\{\{link\}\}/g, problemLink)
        .replace(/\{\{tier\}\}/g, tierText);
};

/**
 * 템플릿에 기본 섹션 추가 (제출한 코드, 문제 링크, Generated by DidimLog)
 * 모든 템플릿(시스템/커스텀)에 일관되게 적용
 */
const ensureDefaultSections = (
    templateContent: string,
    problemId: string,
    tier?: string | null
): string => {
    // 중복된 "제출한 코드" 섹션 제거
    let cleanedContent = removeDuplicateCodeSections(templateContent);
    
    // 기존 메타 정보 제거 (중복 방지)
    // 마지막에 있는 --- 이후의 메타 정보 제거
    cleanedContent = cleanedContent.replace(/\n---\n.*\[문제 링크\].*Generated by DidimLog.*$/s, '').trim();
    
    // "## 제출한 코드" 섹션 패턴 확인
    const codeSectionPattern = /##\s*제출한\s*코드[\s\S]*?```[\s\S]*?```/i;
    const hasCompleteCodeSection = codeSectionPattern.test(cleanedContent);
    
    // 기본 섹션 배열
    const defaultSections: string[] = [];
    
    // 완전한 "## 제출한 코드" 섹션이 없으면 추가
    if (!hasCompleteCodeSection) {
        // 불완전한 섹션 제거 (헤더만 있고 코드 블록이 없는 경우)
        cleanedContent = cleanedContent.replace(/##\s*제출한\s*코드\s*\n?/gi, '').trim();
        
        defaultSections.push('## 제출한 코드');
        defaultSections.push('```kotlin\n여기에 코드를 작성하세요.\n```');
    }
    
    // 구분선과 메타 정보는 항상 마지막에 추가
    defaultSections.push('---');
    defaultSections.push(`[문제 링크]({{link}}) | 티어: {{tier}}`);
    defaultSections.push('Generated by DidimLog');
    
    // 마지막에 기본 섹션 추가
    const contentWithDefaults = cleanedContent + '\n\n' + defaultSections.join('\n\n');
    
    // 플레이스홀더를 실제 값으로 치환
    return replacePlaceholders(contentWithDefaults, problemId, tier);
};

/**
 * 템플릿의 코드 블록에 제출한 코드를 삽입
 * 코드 블록 패턴: ```language\n...\n```
 * "제출한 코드" 섹션의 빈 코드 블록에만 코드를 채움
 */
const insertCodeIntoTemplate = (templateContent: string, code: string, programmingLanguage: string): string => {
    if (!code || !code.trim()) {
        return templateContent;
    }

    const normalizedLang = programmingLanguage.toLowerCase();
    
    // "제출한 코드" 섹션을 찾기
    const 제출한코드SectionPattern = /##\s*제출한\s*코드[\s\S]*?```(\w+)?\n([\s\S]*?)```/i;
    const match = templateContent.match(제출한코드SectionPattern);
    
    if (match) {
        const lang = match[1];
        const existingContent = match[2];
        const trimmedContent = existingContent.trim();
        
        // 플레이스홀더가 있거나 빈 경우에만 코드 삽입
        if (!trimmedContent || 
            trimmedContent.includes('여기에 코드를 작성하세요') || 
            trimmedContent.includes('Write your code here') ||
            trimmedContent === '') {
            
            // 언어 태그가 없거나 'text'인 경우 프로그래밍 언어 사용
            const codeLanguage = (lang && lang !== 'text') ? lang : (normalizedLang !== 'text' ? normalizedLang : 'text');
            
            // 코드 블록 교체
            return templateContent.replace(
                /(##\s*제출한\s*코드[\s\S]*?)```(\w+)?\n([\s\S]*?)```/i,
                `$1\`\`\`${codeLanguage}\n${code.trim()}\n\`\`\``
            );
        }
    }
    
    // "제출한 코드" 섹션을 찾지 못한 경우, 첫 번째 빈 코드 블록에 삽입
    const codeBlockPattern = /```(\w+)?\n([\s\S]*?)```/g;
    let isReplaced = false;
    
    const result = templateContent.replace(codeBlockPattern, (match, lang, existingContent) => {
        if (isReplaced) {
            return match; // 이미 교체했으면 그대로 반환
        }
        
        const trimmedContent = existingContent.trim();
        
        // 빈 코드 블록이나 플레이스홀더가 있는 경우에만 삽입
        if (!trimmedContent || 
            trimmedContent.includes('여기에 코드를 작성하세요') || 
            trimmedContent.includes('Write your code here')) {
            
            isReplaced = true;
            const codeLanguage = (lang && lang !== 'text') ? lang : (normalizedLang !== 'text' ? normalizedLang : 'text');
            return `\`\`\`${codeLanguage}\n${code.trim()}\n\`\`\``;
        }
        
        return match;
    });
    
    return result;
};

export const RetrospectiveWritePage: FC = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const [searchParams] = useSearchParams();
    const createMutation = useCreateRetrospective();
    const updateMutation = useUpdateRetrospective();
    const { completePhase } = useOnboardingStore();
    const {
        data: templateSummaries,
        isLoading: isTemplateSummariesLoading,
        error: templateSummariesError,
    } = useTemplateSummaries();
    const { data: templatesRaw, isLoading: isTemplatesLoading } = useTemplates();
    const renderTemplateMutation = useRenderTemplate();
    const templates = useMemo<TemplateSummary[]>(() => {
        if (templateSummaries && templateSummaries.length > 0) {
            return templateSummaries;
        }
        if (templatesRaw && templatesRaw.length > 0) {
            return templatesRaw.map((template) => ({
                id: template.id,
                studentId: template.studentId,
                title: template.title,
                type: template.type,
                isDefaultSuccess: template.isDefaultSuccess,
                isDefaultFail: template.isDefaultFail,
                createdAt: template.createdAt,
                updatedAt: template.updatedAt,
            }));
        }
        return [];
    }, [templateSummaries, templatesRaw]);

    const isOnboarding = searchParams.get('onboarding') === 'true';
    const queryRetrospectiveId = searchParams.get('retrospectiveId') || '';

    const [retrospectiveId, setRetrospectiveId] = useState<string | null>(null);
    const [problemId, setProblemId] = useState<string>('');
    const [isSuccess, setIsSuccess] = useState<boolean>(false);
    const [resultType, setResultType] = useState<ProblemResult>('FAIL');
    const [content, setContent] = useState<string>('');
    const [summary, setSummary] = useState<string>('');
    const [code, setCode] = useState<string>('');
    const [logId, setLogId] = useState<string | null>(null);
    const [solveTime, setSolveTime] = useState<string | null>(null);
    const [language, setLanguage] = useState<string>('text');
    const [isLoadingTemplate, setIsLoadingTemplate] = useState(false);
    const [hasLoadedTemplate, setHasLoadedTemplate] = useState(false);
    const [selectedTemplateId, setSelectedTemplateId] = useState<string | null>(null);
    const [templateFallbackInfo, setTemplateFallbackInfo] = useState<TemplateFallbackInfo | null>(null);
    const [isPageStateReady, setIsPageStateReady] = useState(false);
    const [editorKey, setEditorKey] = useState<number>(Date.now());
    const templateLoadRequestIdRef = useRef(0);
    const templateContextKeyRef = useRef<string | null>(null);
    const templateAbortControllerRef = useRef<AbortController | null>(null);
    const editHydratedRef = useRef<string | null>(null);

    // 문제 상세 정보 조회
    const effectiveRetrospectiveId = retrospectiveId || queryRetrospectiveId;
    const { data: retrospectiveForEdit, isLoading: isLoadingRetrospectiveForEdit } = useRetrospective(
        effectiveRetrospectiveId || ''
    );
    const { data: problem, isLoading: isProblemLoading } = useProblemDetail(problemId);

    const category: 'SUCCESS' | 'FAIL' = isSuccess ? 'SUCCESS' : 'FAIL';
    const representativeCategories = useMemo(
        () => buildRepresentativeCategoriesFromSource(problem ?? {}, 8),
        [problem]
    );
    const isMissingProblemContext = isPageStateReady && !problemId && !effectiveRetrospectiveId;
    const isLoadingEditRetrospective =
        Boolean(effectiveRetrospectiveId) &&
        isLoadingRetrospectiveForEdit &&
        !hasLoadedTemplate &&
        !content.trim();

    /**
     * 템플릿 렌더링 및 에디터에 적용
     */
    const loadTemplate = useCallback(
        async (templateId: string, pid: string) => {
            if (!pid || !templateId) {
                return;
            }

            const requestId = ++templateLoadRequestIdRef.current;
            templateAbortControllerRef.current?.abort();
            const abortController = new AbortController();
            templateAbortControllerRef.current = abortController;
            setIsLoadingTemplate(true);
            setTemplateFallbackInfo(null);
            try {
                const problemIdNum = parseInt(pid, 10);
                if (isNaN(problemIdNum)) {
                    throw new Error('Invalid problem ID');
                }

                // 프로그래밍 언어 코드 변환 (소문자 -> 대문자)
                // 예: "kotlin" -> "KOTLIN", "java" -> "JAVA"
                const programmingLanguageValue = language && language !== 'text' ? language.toUpperCase() : null;
                
                // 코드와 프로그래밍 언어를 백엔드에 전달하여 코드 블록 언어 태그 자동 처리
                const result = await renderTemplateMutation.mutateAsync({
                    templateId,
                    problemId: problemIdNum,
                    code: code || null, // 제출한 코드가 있으면 전달 (백엔드에서 언어 자동 감지에 사용)
                    programmingLanguage: programmingLanguageValue, // 선택된 언어가 있으면 전달 (코드 블록 언어 태그로 사용)
                    signal: abortController.signal,
                });

                // 템플릿 내용 처리
                let templateContent = result.renderedContent;
                
                // 제목 생성에 필요한 정보 준비
                const problemTitle = problem?.title || '문제';
                // 성공: 해결 회고, 실패: 미해결 회고
                const resultText = isSuccess ? '해결' : '미해결';
                const formattedTitle = formatTitle(DEFAULT_TITLE_FORMAT, {
                    problemId: pid,
                    problemTitle,
                    language,
                    result: resultText,
                });
                
                if (!templateContent || templateContent.trim() === '') {
                    // 템플릿이 비어있을 때 기본 제목 형식 사용
                    templateContent = `${formattedTitle}\n\n`;
                } else {
                    // 템플릿 내용의 첫 번째 줄이 제목인지 확인
                    const lines = templateContent.split('\n');
                    const firstLine = lines[0]?.trim() || '';
                    
                    // 첫 번째 줄이 `#`로 시작하는 경우 (제목이 있는 경우)
                    if (firstLine.startsWith('#')) {
                        // 기존 제목을 새로운 형식으로 교체
                        // `#`, `##`, `# #`, `## #` 등 모든 경우 처리
                        lines[0] = formattedTitle;
                        templateContent = lines.join('\n');
                    }
                    // 첫 번째 줄이 `#`로 시작하지 않으면 제목 추가
                    else {
                        templateContent = `${formattedTitle}\n\n${templateContent}`;
                    }
                }

                // 백엔드에서 코드 블록의 언어 태그를 자동으로 처리합니다
                // (programmingLanguage 또는 code를 통해)
                // 또한 백엔드에서 코드 블록에 코드를 자동으로 채워줄 수 있지만,
                // 프론트엔드에서도 추가로 확인하여 빈 코드 블록에 코드 삽입

                // 티어 정보 가져오기
                const tierText = problem?.difficulty && problem?.difficultyLevel
                    ? formatTierFromDifficulty(problem.difficulty, problem.difficultyLevel)
                    : null;
                
                // 모든 템플릿에 기본 섹션 보장 (제출한 코드, 문제 링크, Generated by DidimLog)
                // 플레이스홀더도 실제 값으로 치환
                templateContent = ensureDefaultSections(templateContent, pid, tierText);
                
                // 제출한 코드가 있으면 코드 블록에 자동으로 채우기
                if (code && code.trim()) {
                    templateContent = insertCodeIntoTemplate(templateContent, code, language);
                }

                if (requestId !== templateLoadRequestIdRef.current) {
                    return;
                }
                setContent(templateContent);
                setSelectedTemplateId(templateId);
                if (result.fallbackUsed) {
                    const fallbackReason = result.fallbackReason ?? null;
                    setTemplateFallbackInfo({ reason: fallbackReason });
                    toast.warning(getTemplateFallbackMessage(fallbackReason));
                } else {
                    setTemplateFallbackInfo(null);
                }
                setHasLoadedTemplate(true);
            } catch (error: unknown) {
                if (requestId !== templateLoadRequestIdRef.current) {
                    return;
                }
                if (isApiError(error) && error.code === 'ERR_CANCELED') {
                    return;
                }
                if (isApiError(error) && error.response?.status === 404) {
                    toast.error('선택한 템플릿을 찾을 수 없어 기본 템플릿으로 전환합니다.');
                } else if (
                    isApiError(error) &&
                    (
                        error.response?.status === 504 ||
                        error.response?.data?.code === 'TEMPLATE_RENDER_TIMEOUT' ||
                        error.code === 'ECONNABORTED'
                    )
                ) {
                    toast.error(getTemplateFallbackMessage('TEMPLATE_RENDER_TIMEOUT'));
                } else if (isApiError(error) && error.response?.data?.retryable) {
                    toast.error('템플릿을 일시적으로 불러오지 못했습니다. 기본 템플릿으로 전환합니다.');
                } else {
                    toast.error('템플릿을 불러오는 중 오류가 발생했습니다.');
                }
                // Fallback: 최소한의 기본 템플릿 제공 (문제 제목 포함)
                const problemTitle = problem?.title || '문제';
                const resultText = isSuccess ? '해결' : '미해결';
                const formattedTitle = formatTitle(DEFAULT_TITLE_FORMAT, {
                    problemId: pid,
                    problemTitle,
                    language,
                    result: resultText,
                });
                const tierText = problem?.difficulty && problem?.difficultyLevel
                    ? formatTierFromDifficulty(problem.difficulty, problem.difficultyLevel)
                    : null;
                const fallbackTemplate = ensureDefaultSections(
                    `${formattedTitle}\n\n## 접근 방법\n\n## 복잡도 분석\n\n`,
                    pid,
                    tierText
                );
                setSelectedTemplateId(templateId);
                setContent(fallbackTemplate);
                setTemplateFallbackInfo({
                    reason: isApiError(error) ? (error.response?.data?.code ?? null) : null,
                });
                setHasLoadedTemplate(true);
            } finally {
                if (templateAbortControllerRef.current === abortController) {
                    templateAbortControllerRef.current = null;
                }
                if (requestId === templateLoadRequestIdRef.current) {
                    setIsLoadingTemplate(false);
                }
            }
        },
        [renderTemplateMutation, problem, language, isSuccess, code]
    );

    const loadDefaultTemplate = useCallback(
        async (pid: string, forceReload: boolean = false) => {
            if (isLoadingTemplate) {
                return;
            }
            if (templateAbortControllerRef.current) {
                return;
            }

            if (hasLoadedTemplate && !forceReload) {
                return;
            }

            if (!templates || templates.length === 0) {
                return;
            }

            const detailFallback = templates.find((t) =>
                t.title.toLowerCase().includes('detail') || t.title.includes('상세')
            );
            const simpleFallback = templates.find((t) =>
                t.title.toLowerCase().includes('simple') || t.title.includes('요약')
            );

            // 카테고리별 기본 템플릿 찾기
            const categoryTemplate = templates.find((t) => 
                category === 'SUCCESS' ? t.isDefaultSuccess : t.isDefaultFail
            );

            const fallbackTemplate = category === 'SUCCESS' ? simpleFallback : detailFallback;
            const selectedTemplate = categoryTemplate || fallbackTemplate || templates[0];
            if (selectedTemplate) {
                setSelectedTemplateId(selectedTemplate.id);
                await loadTemplate(selectedTemplate.id, pid);
            }
        },
        [templates, hasLoadedTemplate, category, loadTemplate, isLoadingTemplate]
    );

    // 온보딩 모드: 자동으로 폼 열기 (AI 버튼이 보이도록)
    useEffect(() => {
        if (isOnboarding && !isSuccess && problemId) {
            // 온보딩 모드이고 문제 ID가 있으면 자동으로 SUCCESS 상태로 설정
            setIsSuccess(true);
        }
    }, [isOnboarding, isSuccess, problemId]);

    useEffect(() => {
        if (resultType === 'TIME_OVER') {
            return;
        }
        setResultType(isSuccess ? 'SUCCESS' : 'FAIL');
    }, [isSuccess, resultType]);


    useEffect(() => {
        // location.state에서 전달된 데이터 확인 (초기 상태만 반영)
        const state = location.state as {
            retrospectiveId?: string;
            problemId?: string;
            template?: string;
            isSuccess?: boolean;
            code?: string;
            logId?: string | null;
            solveTime?: string | null;
            language?: string;
            initialSummary?: string; // 한 줄 요약 추가
            initialSolvedCategory?: string; // 풀이 전략 태그 추가
            status?: string; // 추가: 명시적 status 전달 (SOLVED/FAIL)
        } | null;

        const queryProblemId = searchParams.get('problemId') || '';
        const queryStatus = searchParams.get('status') || '';
        const queryRetroId = searchParams.get('retrospectiveId') || '';

        if (state) {
            const { retrospectiveId: retroId, problemId: pid, template: temp, isSuccess: success, code: codeValue, logId: createdLogId, solveTime: stateSolveTime, language: stateLanguage, initialSummary: stateSummary, status: stateStatus } = state;
            const effectiveStateRetroId = retroId || queryRetroId;
            
            // 수정 모드인 경우 retrospectiveId 설정
            if (effectiveStateRetroId) {
                setRetrospectiveId(effectiveStateRetroId);
            }
            
            // problemId 설정 (최우선)
            if (pid) {
                setProblemId(pid);
            }
            
            // isSuccess 설정: status 우선, 없으면 isSuccess 사용, 둘 다 없으면 false
            const finalIsSuccess = stateStatus === 'SOLVED' || stateStatus === 'SUCCESS' 
                ? true 
                : (success !== undefined ? success : false);
            setIsSuccess(finalIsSuccess);
            const finalResultType: ProblemResult = stateStatus === 'TIME_OVER'
                ? 'TIME_OVER'
                : finalIsSuccess
                    ? 'SUCCESS'
                    : 'FAIL';
            setResultType(finalResultType);
            setLogId(createdLogId ?? null);
            setCode(codeValue ?? '');
            setSolveTime(stateSolveTime ?? null);
            setLanguage(stateLanguage ?? 'text');
            setSummary(stateSummary ?? ''); // 한 줄 요약 설정
            
            // 템플릿 로드 우선순위:
            // 1. 수정 모드에서는 기존 회고 내용을 우선 사용
            if (temp && effectiveStateRetroId) {
                setContent(temp);
                setHasLoadedTemplate(true);
                editHydratedRef.current = effectiveStateRetroId;
                setEditorKey(Date.now());
            }
        }
        if (!state?.retrospectiveId && queryRetroId) {
            setRetrospectiveId(queryRetroId);
        }
        if (!state?.problemId && queryProblemId) {
            setProblemId(queryProblemId);
        }
        if (!state?.status && queryStatus) {
            const normalizedQueryStatus = queryStatus.toUpperCase();
            if (normalizedQueryStatus === 'TIME_OVER') {
                setIsSuccess(false);
                setResultType('TIME_OVER');
            } else if (normalizedQueryStatus === 'SUCCESS' || normalizedQueryStatus === 'SOLVED') {
                setIsSuccess(true);
                setResultType('SUCCESS');
            } else if (normalizedQueryStatus === 'FAIL') {
                setIsSuccess(false);
                setResultType('FAIL');
            }
        }
        setIsPageStateReady(true);
    }, [location.state, searchParams]);

    useEffect(() => {
        if (!effectiveRetrospectiveId || !retrospectiveForEdit) {
            return;
        }
        if (editHydratedRef.current === effectiveRetrospectiveId) {
            return;
        }

        const normalizedResult = (retrospectiveForEdit.solutionResult || '').toUpperCase();
        const hydratedIsSuccess = normalizedResult === 'SUCCESS' || normalizedResult === 'SOLVED';
        const hydratedResultType: ProblemResult =
            normalizedResult === 'TIME_OVER' ? 'TIME_OVER' : hydratedIsSuccess ? 'SUCCESS' : 'FAIL';

        setRetrospectiveId(retrospectiveForEdit.id);
        setProblemId(retrospectiveForEdit.problemId);
        setIsSuccess(hydratedIsSuccess);
        setResultType(hydratedResultType);
        setSummary(retrospectiveForEdit.summary || '');
        setSolveTime(retrospectiveForEdit.solveTime || null);
        setContent(retrospectiveForEdit.content || '');
        setHasLoadedTemplate(true);
        setTemplateFallbackInfo(null);
        setEditorKey(Date.now());
        editHydratedRef.current = effectiveRetrospectiveId;
    }, [effectiveRetrospectiveId, retrospectiveForEdit]);

    // 문제/결과 컨텍스트가 바뀌면 이전 템플릿 상태를 무효화하여 잘못된 템플릿 잔존을 방지
    useEffect(() => {
        if (!problemId || retrospectiveId) {
            return;
        }
        const contextKey = `${problemId}:${category}`;
        if (templateContextKeyRef.current === contextKey) {
            return;
        }
        templateContextKeyRef.current = contextKey;
        templateLoadRequestIdRef.current += 1;
        templateAbortControllerRef.current?.abort();
        templateAbortControllerRef.current = null;
        setIsLoadingTemplate(false);
        setHasLoadedTemplate(false);
        setSelectedTemplateId(null);
        setTemplateFallbackInfo(null);
        setContent('');
    }, [problemId, category, retrospectiveId]);

    useEffect(() => {
        return () => {
            templateAbortControllerRef.current?.abort();
        };
    }, []);

    // templates가 로드된 후 또는 isSuccess 변경 시 기본 템플릿 자동 로드
    useEffect(() => {
        if (!isPageStateReady) {
            return;
        }
        if (isLoadingTemplate) {
            return;
        }
        if (problemId && !hasLoadedTemplate && !retrospectiveId) {
            // 카테고리별 기본 템플릿이 로드되면 자동으로 적용
            if (templates.length > 0) {
                // 템플릿 목록이 있으면 로드 시도
                loadDefaultTemplate(problemId).catch(() => {
                    // Template load failed
                });
            } else if (!isTemplateSummariesLoading && !isTemplatesLoading) {
                // 템플릿 목록 조회 실패/빈 결과 시 최소 기본 템플릿으로 즉시 진행 (빈 에디터 방지)
                const problemTitle = problem?.title || '문제';
                const resultText = isSuccess ? '해결' : '미해결';
                const formattedTitle = formatTitle(DEFAULT_TITLE_FORMAT, {
                    problemId,
                    problemTitle,
                    language,
                    result: resultText,
                });
                const tierText = problem?.difficulty && problem?.difficultyLevel
                    ? formatTierFromDifficulty(problem.difficulty, problem.difficultyLevel)
                    : null;
                const emergencyTemplate = ensureDefaultSections(
                    `${formattedTitle}\n\n## 접근 방법\n\n## 복잡도 분석\n\n`,
                    problemId,
                    tierText
                );
                setContent(emergencyTemplate);
                setTemplateFallbackInfo({
                    reason: templateSummariesError ? 'TEMPLATE_LIST_UNAVAILABLE' : 'TEMPLATE_NOT_CONFIGURED',
                });
                setHasLoadedTemplate(true);
                if (templateSummariesError) {
                    toast.error('템플릿 목록 조회에 실패하여 기본 템플릿을 적용했습니다.');
                }
            }
        }
    }, [
        problemId,
        hasLoadedTemplate,
        retrospectiveId,
        templates,
        loadDefaultTemplate,
        isPageStateReady,
        isTemplateSummariesLoading,
        isTemplatesLoading,
        templateSummariesError,
        isLoadingTemplate,
        problem,
        isSuccess,
        language,
    ]);

    // code가 설정된 후 이미 템플릿이 로드되었고 코드 블록이 비어있으면 코드 삽입
    useEffect(() => {
        if (code && code.trim() && selectedTemplateId && problemId && hasLoadedTemplate && !retrospectiveId && content) {
            // 현재 content에 빈 코드 블록이 있는지 확인
            // 패턴: ```language\n여기에 코드를 작성하세요\n``` 또는 ```language\n\n``` 또는 ```language\n```
            const hasEmptyCodeBlock = /```\w*\n\s*(여기에 코드를 작성하세요|Write your code here|)\s*```/i.test(content) ||
                /```\w*\n\s*```/.test(content) ||
                /##\s*제출한\s*코드[\s\S]*?```\w*\n\s*```/i.test(content);
            
            if (hasEmptyCodeBlock) {
                // 코드 블록이 비어있으면 코드를 삽입하여 content 업데이트
                const updatedContent = insertCodeIntoTemplate(content, code, language);
                if (updatedContent !== content) {
                    setContent(updatedContent);
                }
            }
        }
    }, [code, selectedTemplateId, problemId, hasLoadedTemplate, retrospectiveId, content, language]);

    const handleCopyMarkdown = async () => {
        if (!content.trim() || !problemId) {
            toast.error('복사할 내용이 없습니다.');
            return;
        }

        // AI Generated 문구 제거 (푸터는 백엔드/AI에서 이미 포함되어 있으므로 추가하지 않음)
        let markdownContent = content.trim();
        
        // AI Generated 관련 문구 제거 (대소문자 무관)
        markdownContent = markdownContent
            .replace(/AI Generated/gi, '')
            .replace(/AI generated/gi, '')
            .replace(/Generated by AI/gi, '')
            .replace(/generated by ai/gi, '')
            .replace(/AI가 생성/gi, '')
            .replace(/자동 생성/gi, '')
            .trim();

        try {
            await navigator.clipboard.writeText(markdownContent);
            toast.success('마크다운이 클립보드에 복사되었습니다!');
        } catch {
            toast.error('클립보드 복사에 실패했습니다. 브라우저 권한을 확인해주세요.');
        }
    };

    const handleSubmit = async (data: RetrospectiveRequest) => {
        if (!problemId) {
            toast.error('문제 ID가 없습니다.');
            return;
        }

        try {
            // resultType은 화면 컨텍스트 기준으로 자동 설정 (SUCCESS/FAIL/TIME_OVER)
            const finalData: RetrospectiveRequest = {
                ...data,
                resultType,
            };

            // 수정 모드인 경우
            if (retrospectiveId) {
                await updateMutation.mutateAsync({ retrospectiveId, data: finalData });
                toast.success('회고가 수정되었습니다.');
                navigate(`/retrospectives/${retrospectiveId}`);
            } else {
                // 새로 작성하는 경우
                await createMutation.mutateAsync({ problemId, data: finalData });
                toast.success('회고가 저장되었습니다.');
                
                // 온보딩 Phase 완료 처리
                completePhase('retrospective');
                
                navigate('/retrospectives');
            }
        } catch (error: unknown) {
            const errorMessage = getErrorMessage(error);
            
            // 백엔드에서 소유자 검증 실패 시
            if (isApiError(error) && (error.response?.status === 403 || error.response?.status === 400)) {
                toast.error('본인이 작성한 회고만 수정할 수 있습니다.');
            } else {
                toast.error(errorMessage);
            }
        }
    };

    const handleContentChange = (newContent: string) => {
        setContent(newContent);
    };

    /**
     * 템플릿 변경 핸들러
     */
    const handleTemplateChange = async (templateId: string) => {
        if (templateId === selectedTemplateId) {
            return;
        }

        // 사용자가 이미 내용을 작성 중이면 확인 다이얼로그 표시
        const hasUserContent = content.trim() !== '';

        if (hasUserContent) {
            const confirmed = window.confirm('템플릿을 변경하면 현재 작성 중인 내용이 덮어씌워집니다. 계속하시겠습니까?');
            if (!confirmed) {
                return;
            }
        }

        if (problemId) {
            await loadTemplate(templateId, problemId);
            setEditorKey(Date.now());
        }
    };

    return (
        <Layout>
            <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
                <div className="max-w-4xl mx-auto space-y-8">
                    {/* 🎨 Global Header - 표준화된 네비게이션 */}
                    {problemId && (
                        <div className="flex items-center justify-between mb-6">
                            {/* 왼쪽: 네비게이션 & 제목 */}
                            <div className="flex-1 min-w-0">
                                {isProblemLoading ? (
                                    <div className="flex items-center gap-3">
                                        <Spinner />
                                        <span className="text-gray-600 dark:text-gray-400">문제 정보를 불러오는 중...</span>
                                    </div>
                                ) : problem ? (
                                    <div className="flex items-center gap-3">
                                        {/* 이전 버튼 (아이콘만) */}
                                        <button
                                            onClick={() => navigate(-1)}
                                            className="flex-shrink-0 p-1.5 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
                                            title="이전 페이지로"
                                        >
                                            <ChevronLeft className="w-5 h-5" />
                                        </button>
                                        {/* 문제 번호 & 태그 */}
                                        <div className="flex items-center gap-3 flex-wrap">
                                                {/* 태그 */}
                                                <div className="flex items-center gap-2 flex-wrap">
                                                    <span className="px-2 py-1 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 rounded text-sm font-medium">
                                                        {representativeCategories[0]
                                                            ? getCategoryLabel(representativeCategories[0])
                                                            : problem.category}
                                                    </span>
                                                <span className={`px-2 py-1 rounded text-sm font-medium whitespace-nowrap ${getTierColor(problem.difficulty)}`}>
                                                    {formatTierFromDifficulty(problem.difficulty, problem.difficultyLevel)}
                                                </span>
                                                {/* 언어 배지 */}
                                                <LanguageBadge language={language} />
                                                {/* 알고리즘 태그 */}
                                                {representativeCategories.length > 1 ? (
                                                    <>
                                                        {representativeCategories.slice(1, 6).map((tag, index) => (
                                                            <span
                                                                key={index}
                                                                className="px-2 py-0.5 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded text-xs"
                                                            >
                                                                {getCategoryLabel(tag)}
                                                            </span>
                                                        ))}
                                                    </>
                                                ) : problem.tags && problem.tags.length > 0 ? (
                                                    <>
                                                        {problem.tags.map((tag, index) => (
                                                            <span
                                                                key={index}
                                                                className="px-2 py-0.5 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded text-xs"
                                                            >
                                                                {tag}
                                                            </span>
                                                        ))}
                                                    </>
                                                ) : null}
                                            </div>
                                        </div>
                                    </div>
                                ) : (
                                    <div className="flex items-center gap-3">
                                        <button
                                            onClick={() => navigate(-1)}
                                            className="flex-shrink-0 p-1.5 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
                                            title="이전 페이지로"
                                        >
                                            <ChevronLeft className="w-5 h-5" />
                                        </button>
                                        <p className="text-gray-600 dark:text-gray-400">문제 #{problemId} 정보를 불러올 수 없습니다.</p>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}

                    {/* 헤더 (액션 버튼) */}
                    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-6 border border-gray-200 dark:border-gray-700">
                        <div className="flex items-center justify-between">
                            <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
                                {retrospectiveId ? '회고 수정' : '회고 작성'}
                            </h2>
                            <div className="flex items-center gap-3">
                                <Button 
                                    onClick={handleCopyMarkdown} 
                                    variant="outline" 
                                    className="flex items-center gap-2"
                                >
                                    <Copy className="w-4 h-4" />
                                    Markdown 복사
                                </Button>
                            </div>
                        </div>
                    </div>

                    {/* AI 한 줄 인사이트 (회고 작성 헤더 아래, 한 줄 요약 위) */}
                    <div className="mb-6 tour-ai-section">
                        <AiReviewCard 
                            logId={logId} 
                            code={code}
                            isSuccess={isSuccess}
                            problemId={problemId}
                            problemTitle={problem?.title}
                        />
                    </div>

                    {isMissingProblemContext && (
                        <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-xl p-4">
                            <p className="text-sm text-yellow-800 dark:text-yellow-200">
                                문제 정보가 없어 기본 템플릿을 적용할 수 없습니다. 문제/스터디 화면에서 다시 회고 작성을 시작해주세요.
                            </p>
                        </div>
                    )}

                    {isLoadingTemplate && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-8 border border-gray-200 dark:border-gray-700">
                            <div className="flex items-center justify-center py-12">
                                <Spinner />
                                <span className="ml-3 text-gray-600 dark:text-gray-400">템플릿을 불러오는 중...</span>
                            </div>
                        </div>
                    )}

                    {/* 템플릿 선택 드롭다운 */}
                    {isLoadingEditRetrospective && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-8 border border-gray-200 dark:border-gray-700">
                            <div className="flex items-center justify-center py-8">
                                <Spinner />
                                <span className="ml-3 text-gray-600 dark:text-gray-400">기존 회고를 불러오는 중...</span>
                            </div>
                        </div>
                    )}

                    {!isLoadingTemplate && !retrospectiveId && problemId && templates && templates.length > 0 && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-4 border border-gray-200 dark:border-gray-700">
                            <div className="flex items-center gap-3">
                                <label htmlFor="template-select" className="text-sm font-medium text-gray-700 dark:text-gray-300">
                                    템플릿 선택:
                                </label>
                                <select
                                    id="template-select"
                                    value={selectedTemplateId || ''}
                                    onChange={(e) => {
                                        if (e.target.value) {
                                            handleTemplateChange(e.target.value);
                                        }
                                    }}
                                    className="flex-1 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                                >
                                    {templates.map((template) => (
                                        <option key={template.id} value={template.id}>
                                            {template.isDefaultSuccess ? '✅ ' : ''}
                                            {template.isDefaultFail ? '❌ ' : ''}
                                            {template.type === 'SYSTEM' ? '🔧 ' : ''}
                                            {template.title}
                                        </option>
                                    ))}
                                </select>
                            </div>
                        </div>
                    )}

                    {!isLoadingTemplate && retrospectiveId && (
                        <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-xl px-4 py-3">
                            <p className="text-sm text-blue-800 dark:text-blue-200">
                                수정 모드에서는 저장된 회고 내용을 기준으로 편집합니다.
                            </p>
                        </div>
                    )}

                    {!isLoadingTemplate && templateFallbackInfo && (
                        <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-xl px-4 py-3">
                            <div className="flex items-center gap-2">
                                <span className="inline-flex items-center rounded-full bg-amber-100 dark:bg-amber-900/40 px-2 py-1 text-xs font-semibold text-amber-800 dark:text-amber-200">
                                    템플릿 fallback 적용
                                </span>
                                <p className="text-sm text-amber-800 dark:text-amber-200">
                                    {getTemplateFallbackMessage(templateFallbackInfo.reason)}
                                </p>
                            </div>
                        </div>
                    )}

                    {/* 회고 에디터 */}
                    {!isLoadingTemplate && !isLoadingEditRetrospective && !isMissingProblemContext && (
                        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-md p-8 border border-gray-200 dark:border-gray-700">
                            <RetrospectiveEditor
                                key={editorKey}
                                initialContent={content}
                                initialSummary={summary}
                                initialSolvedCategory={location.state?.initialSolvedCategory}
                                onSubmit={(data) => {
                                    handleSubmit({
                                        ...data,
                                        solveTime: solveTime || data.solveTime,
                                    });
                                }}
                                isLoading={createMutation.isPending || updateMutation.isPending}
                                onContentChange={handleContentChange}
                                recommendedTags={representativeCategories}
                            />
                        </div>
                    )}
                </div>
            </div>
        </Layout>
    );
};
