/**
 * 회고 상세 페이지
 */

import type { FC } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useRetrospective, useDeleteRetrospective } from '../../../hooks/api/useRetrospective';
import { useProblemDetail } from '../../../hooks/api/useProblem';
import { Spinner } from '../../../components/ui/Spinner';
import { Layout } from '../../../components/layout/Layout';
import { Button } from '../../../components/ui/Button';
import { useAuthStore } from '../../../stores/auth.store';
import { toast } from 'sonner';
import { Copy, Trash2, Edit } from 'lucide-react';

export const RetrospectiveDetailPage: FC = () => {
    const { id } = useParams<{ id: string }>();
    const navigate = useNavigate();
    const { user, token } = useAuthStore();
    const { data: retrospective, isLoading, error } = useRetrospective(id || '');
    const { data: problem, isLoading: isProblemLoading } = useProblemDetail(retrospective?.problemId || '');
    const deleteMutation = useDeleteRetrospective();

    const handleDelete = async () => {
        if (!id) {
            toast.error('회고 ID를 찾을 수 없습니다.');
            return;
        }

        if (!token) {
            toast.error('로그인이 필요합니다.');
            return;
        }

        if (!confirm('정말로 삭제하시겠습니까?')) {
            return;
        }

        try {
            await deleteMutation.mutateAsync(id);
            toast.success('회고가 삭제되었습니다.');
            navigate('/retrospectives');
        } catch (error: any) {
            console.error('Delete failed:', error);
            const errorMessage = error?.response?.data?.message || error?.message || '회고 삭제에 실패했습니다.';
            
            // 백엔드에서 소유자 검증 실패 시
            if (error?.response?.status === 403 || error?.response?.status === 400) {
                toast.error('본인이 작성한 회고만 삭제할 수 있습니다.');
            } else {
                toast.error(errorMessage);
            }
        }
    };

    const formatDate = (dateString: string) => {
        const date = new Date(dateString);
        return date.toLocaleString('ko-KR', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        });
    };

    if (isLoading || isProblemLoading) {
        return (
            <Layout>
                <div className="flex items-center justify-center min-h-screen">
                    <Spinner />
                </div>
            </Layout>
        );
    }

    if (error || !retrospective) {
        return (
            <Layout>
                <div className="flex items-center justify-center min-h-screen">
                    <div className="text-center">
                        <h1 className="text-2xl font-bold text-red-600 dark:text-red-400 mb-4">오류가 발생했습니다</h1>
                        <p className="text-gray-600 dark:text-gray-400">
                            {error instanceof Error ? error.message : '회고를 불러올 수 없습니다.'}
                        </p>
                    </div>
                </div>
            </Layout>
        );
    }

    // 소유자 확인: 
    // - user.id는 JWT의 sub (BOJ ID 또는 providerId)
    // - retrospective.studentId는 MongoDB의 Student 엔티티 ID
    // - 따라서 직접 비교할 수 없으므로, 로그인한 사용자면 삭제 버튼을 표시하고
    // - 실제 소유자 검증은 백엔드에서 수행합니다 (API 명세서 참고)
    const isAuthenticated = !!token && !!user;

    // 제목 생성: "1027번 고층 건물 성공 회고" (괄호 제거)
    const getTitle = () => {
        const problemTitle = problem?.title || '문제';
        const resultText = retrospective.solutionResult === 'SUCCESS' ? '성공' : 
                          retrospective.solutionResult === 'FAIL' ? '실패' : 
                          retrospective.solutionResult === 'TIME_OVER' ? '시간 초과' : '';
        const resultPart = resultText ? ` ${resultText}` : '';
        return `${retrospective.problemId}번 ${problemTitle}${resultPart} 회고`;
    };

    const handleCopyMarkdown = async () => {
        if (!retrospective.content.trim()) {
            toast.error('복사할 내용이 없습니다.');
            return;
        }

        // AI Generated 문구 제거 및 출처 푸터 추가
        let markdownContent = retrospective.content.trim();
        
        // AI Generated 관련 문구 제거 (대소문자 무관)
        markdownContent = markdownContent
            .replace(/AI Generated/gi, '')
            .replace(/AI generated/gi, '')
            .replace(/Generated by AI/gi, '')
            .replace(/generated by ai/gi, '')
            .replace(/AI가 생성/gi, '')
            .replace(/자동 생성/gi, '')
            .trim();

        // 출처 푸터 추가
        const footer = '\n\n> _Generated by DidimLog_';
        markdownContent = markdownContent + footer;

        try {
            await navigator.clipboard.writeText(markdownContent);
            toast.success('마크다운이 클립보드에 복사되었습니다. 블로그에 붙여넣으세요!');
        } catch (error) {
            console.error('클립보드 복사 실패:', error);
            toast.error('클립보드 복사에 실패했습니다. 브라우저 권한을 확인해주세요.');
        }
    };

    // 60일 이상 된 회고인지 확인
    const isOldRetrospective = () => {
        const createdAt = new Date(retrospective.createdAt);
        const now = new Date();
        const daysDiff = Math.floor((now.getTime() - createdAt.getTime()) / (1000 * 60 * 60 * 24));
        return daysDiff >= 60;
    };

    return (
        <Layout>
            <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
                <div className="max-w-4xl mx-auto space-y-6">
                    {/* 헤더 */}
                    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border border-gray-200 dark:border-gray-700">
                        <div className="flex items-start justify-between mb-4">
                            <div className="flex-1">
                                <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                                    {getTitle()}
                                </h1>
                                {retrospective.summary && (
                                    <p className="text-gray-600 dark:text-gray-400">{retrospective.summary}</p>
                                )}
                            </div>
                            <div className="flex items-center gap-2">
                                {retrospective.isBookmarked && (
                                    <svg className="w-6 h-6 text-yellow-500" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                                    </svg>
                                )}
                            </div>
                        </div>

                        <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400 flex-wrap">
                            <span>{formatDate(retrospective.createdAt)}</span>
                            {retrospective.solutionResult && (
                                <>
                                    <span>•</span>
                                    <span
                                        className={`px-2 py-1 rounded ${
                                            retrospective.solutionResult === 'SUCCESS'
                                                ? 'bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200'
                                                : 'bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200'
                                        }`}
                                    >
                                        {retrospective.solutionResult}
                                    </span>
                                </>
                            )}
                            {(retrospective.solveTime || retrospective.timeTaken) && (
                                <>
                                    <span>•</span>
                                    <span className="px-2 py-1 bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-300 rounded flex items-center gap-1">
                                        <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                                        </svg>
                                        {retrospective.solveTime || (retrospective.timeTaken ? 
                                            (retrospective.timeTaken < 60 
                                                ? `${retrospective.timeTaken}초` 
                                                : `${Math.floor(retrospective.timeTaken / 60)}분 ${retrospective.timeTaken % 60}초`) 
                                            : '')}
                                    </span>
                                </>
                            )}
                            {retrospective.solvedCategory && (
                                <>
                                    <span>•</span>
                                    <span className="px-2 py-1 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 rounded">
                                        {retrospective.solvedCategory}
                                    </span>
                                </>
                            )}
                        </div>

                    </div>

                    {/* 오래된 회고 경고 배너 */}
                    {isOldRetrospective() && (
                        <div className="bg-yellow-50 dark:bg-yellow-900/30 border-l-4 border-yellow-500 dark:border-yellow-500 rounded-lg p-4 mb-4">
                            <div className="flex items-start gap-3">
                                <svg className="w-5 h-5 text-yellow-600 dark:text-yellow-400 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                                    <path
                                        fillRule="evenodd"
                                        d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
                                        clipRule="evenodd"
                                    />
                                </svg>
                                <div className="flex-1">
                                    <p className="text-sm text-yellow-800 dark:text-yellow-200 font-medium mb-1">
                                        오래된 회고 안내
                                    </p>
                                    <p className="text-sm text-yellow-700 dark:text-yellow-300">
                                        이 회고는 작성된 지 2달이 지났습니다. 안전한 보관을 위해 기술 블로그로 옮기는 것을 추천드려요!
                                    </p>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* 회고 내용 */}
                    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border border-gray-200 dark:border-gray-700">
                        {/* 액션 버튼 (본문 상단) */}
                        <div className="flex items-center justify-end gap-3 mb-6 pb-4 border-b border-gray-200 dark:border-gray-700">
                            <Button
                                onClick={handleCopyMarkdown}
                                variant={isOldRetrospective() ? 'primary' : 'outline'}
                                className={`flex items-center gap-2 ${isOldRetrospective() ? 'bg-blue-600 hover:bg-blue-700 text-white font-semibold' : ''}`}
                            >
                                <Copy className="w-4 h-4" />
                                {isOldRetrospective() ? '📝 블로그용 Markdown 복사' : 'Markdown 복사'}
                            </Button>
                            {isAuthenticated && (
                                <>
                                    <Button
                                        onClick={() => navigate(`/retrospectives/write`, {
                                            state: {
                                                retrospectiveId: retrospective.id,
                                                problemId: retrospective.problemId,
                                                template: retrospective.content,
                                                isSuccess: retrospective.solutionResult === 'SUCCESS',
                                                code: '',
                                                solveTime: retrospective.solveTime,
                                                initialSummary: retrospective.summary || '', // 한 줄 요약 전달
                                                initialSolvedCategory: retrospective.solvedCategory || '', // 풀이 전략 태그 전달
                                            }
                                        })}
                                        variant="outline"
                                        className="flex items-center gap-2"
                                        title="회고 수정 (본인이 작성한 회고만 수정 가능)"
                                    >
                                        <Edit className="w-4 h-4" />
                                        수정
                                    </Button>
                                    <Button
                                        onClick={handleDelete}
                                        variant="danger"
                                        isLoading={deleteMutation.isPending}
                                        className="flex items-center gap-2 px-4 py-2 rounded-lg font-semibold bg-red-600 hover:bg-red-700 text-white"
                                        title="회고 삭제 (본인이 작성한 회고만 삭제 가능)"
                                    >
                                        <Trash2 className="w-4 h-4" />
                                        삭제
                                    </Button>
                                </>
                            )}
                        </div>

                        <div className="prose dark:prose-invert max-w-none prose-headings:font-bold prose-h1:text-3xl prose-h2:text-2xl prose-h3:text-xl prose-code:bg-gray-100 dark:prose-code:bg-gray-800 prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-pre:bg-gray-900 dark:prose-pre:bg-gray-950 prose-pre:text-gray-100">
                            <ReactMarkdown 
                                remarkPlugins={[remarkGfm]}
                                components={{
                                    code: ({ node, inline, className, children, ...props }: any) => {
                                        const match = /language-(\w+)/.exec(className || '');
                                        return !inline && match ? (
                                            <pre className="bg-gray-900 dark:bg-gray-950 text-gray-100 p-4 rounded-lg overflow-x-auto my-4">
                                                <code className={className} {...props}>
                                                    {children}
                                                </code>
                                            </pre>
                                        ) : (
                                            <code className="bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded text-sm" {...props}>
                                                {children}
                                            </code>
                                        );
                                    },
                                }}
                            >
                                {retrospective.content}
                            </ReactMarkdown>
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    );
};

