/**
 * 회고 상세 페이지
 */

import { useParams, useNavigate } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useRetrospective, useDeleteRetrospective } from '../../../hooks/api/useRetrospective';
import { useProblemDetail } from '../../../hooks/api/useProblem';
import { useDashboard } from '../../../hooks/api/useDashboard';
import { Spinner } from '../../../components/ui/Spinner';
import { Layout } from '../../../components/layout/Layout';
import { Button } from '../../../components/ui/Button';
import { useAuthStore } from '../../../stores/auth.store';
import { toast } from 'sonner';
import { Copy, Trash2 } from 'lucide-react';

export const RetrospectiveDetailPage: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    const navigate = useNavigate();
    const { user, token } = useAuthStore();
    const { data: retrospective, isLoading, error } = useRetrospective(id || '');
    const { data: problem, isLoading: isProblemLoading } = useProblemDetail(retrospective?.problemId || '');
    const { data: dashboard } = useDashboard();
    const deleteMutation = useDeleteRetrospective();

    const handleDelete = async () => {
        if (!id) {
            toast.error('회고 ID를 찾을 수 없습니다.');
            return;
        }

        if (!token) {
            toast.error('로그인이 필요합니다.');
            return;
        }

        if (!confirm('정말로 삭제하시겠습니까?')) {
            return;
        }

        try {
            await deleteMutation.mutateAsync(id);
            toast.success('회고가 삭제되었습니다.');
            navigate('/retrospectives');
        } catch (error: any) {
            console.error('Delete failed:', error);
            const errorMessage = error?.response?.data?.message || error?.message || '회고 삭제에 실패했습니다.';
            
            // 백엔드에서 소유자 검증 실패 시
            if (error?.response?.status === 403 || error?.response?.status === 400) {
                toast.error('본인이 작성한 회고만 삭제할 수 있습니다.');
            } else {
                toast.error(errorMessage);
            }
        }
    };

    const formatDate = (dateString: string) => {
        const date = new Date(dateString);
        return date.toLocaleString('ko-KR', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        });
    };

    if (isLoading || isProblemLoading) {
        return (
            <Layout>
                <div className="flex items-center justify-center min-h-screen">
                    <Spinner />
                </div>
            </Layout>
        );
    }

    if (error || !retrospective) {
        return (
            <Layout>
                <div className="flex items-center justify-center min-h-screen">
                    <div className="text-center">
                        <h1 className="text-2xl font-bold text-red-600 dark:text-red-400 mb-4">오류가 발생했습니다</h1>
                        <p className="text-gray-600 dark:text-gray-400">
                            {error instanceof Error ? error.message : '회고를 불러올 수 없습니다.'}
                        </p>
                    </div>
                </div>
            </Layout>
        );
    }

    // 소유자 확인: 
    // - user.id는 JWT의 sub (BOJ ID 또는 providerId)
    // - retrospective.studentId는 MongoDB의 Student 엔티티 ID
    // - 따라서 직접 비교할 수 없으므로, 로그인한 사용자면 삭제 버튼을 표시하고
    // - 실제 소유자 검증은 백엔드에서 수행합니다 (API 명세서 참고)
    const isAuthenticated = !!token && !!user;

    // 제목 생성: "1027번 고층 건물 성공 회고" (괄호 제거)
    const getTitle = () => {
        const problemTitle = problem?.title || '문제';
        const resultText = retrospective.solutionResult === 'SUCCESS' ? '성공' : 
                          retrospective.solutionResult === 'FAIL' ? '실패' : 
                          retrospective.solutionResult === 'TIME_OVER' ? '시간 초과' : '';
        const resultPart = resultText ? ` ${resultText}` : '';
        return `${retrospective.problemId}번 ${problemTitle}${resultPart} 회고`;
    };

    const handleCopyMarkdown = async () => {
        if (!retrospective.content.trim()) {
            toast.error('복사할 내용이 없습니다.');
            return;
        }

        // AI Generated 문구 제거 및 출처 푸터 추가
        let markdownContent = retrospective.content.trim();
        
        // AI Generated 관련 문구 제거 (대소문자 무관)
        markdownContent = markdownContent
            .replace(/AI Generated/gi, '')
            .replace(/AI generated/gi, '')
            .replace(/Generated by AI/gi, '')
            .replace(/generated by ai/gi, '')
            .replace(/AI가 생성/gi, '')
            .replace(/자동 생성/gi, '')
            .trim();

        // 출처 푸터 추가
        const footer = '\n\n> _Generated by DidimLog_';
        markdownContent = markdownContent + footer;

        try {
            await navigator.clipboard.writeText(markdownContent);
            toast.success('복사되었습니다');
        } catch (error) {
            console.error('클립보드 복사 실패:', error);
            toast.error('클립보드 복사에 실패했습니다. 브라우저 권한을 확인해주세요.');
        }
    };

    return (
        <Layout>
            <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8 px-4">
                <div className="max-w-4xl mx-auto space-y-6">
                    {/* 헤더 */}
                    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border border-gray-200 dark:border-gray-700">
                        <div className="flex items-start justify-between mb-4">
                            <div className="flex-1">
                                <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                                    {getTitle()}
                                </h1>
                                {retrospective.summary && (
                                    <p className="text-gray-600 dark:text-gray-400">{retrospective.summary}</p>
                                )}
                            </div>
                            <div className="flex items-center gap-2">
                                {retrospective.isBookmarked && (
                                    <svg className="w-6 h-6 text-yellow-500" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                                    </svg>
                                )}
                            </div>
                        </div>

                        <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                            <span>{formatDate(retrospective.createdAt)}</span>
                            {retrospective.solutionResult && (
                                <>
                                    <span>•</span>
                                    <span
                                        className={`px-2 py-1 rounded ${
                                            retrospective.solutionResult === 'SUCCESS'
                                                ? 'bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200'
                                                : 'bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200'
                                        }`}
                                    >
                                        {retrospective.solutionResult}
                                    </span>
                                </>
                            )}
                            {retrospective.solvedCategory && (
                                <>
                                    <span>•</span>
                                    <span className="px-2 py-1 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 rounded">
                                        {retrospective.solvedCategory}
                                    </span>
                                </>
                            )}
                        </div>

                    </div>

                    {/* 회고 내용 */}
                    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border border-gray-200 dark:border-gray-700">
                        {/* 액션 버튼 (본문 상단) */}
                        <div className="flex items-center justify-end gap-3 mb-6 pb-4 border-b border-gray-200 dark:border-gray-700">
                            <Button
                                onClick={handleCopyMarkdown}
                                variant="outline"
                                className="flex items-center gap-2"
                            >
                                <Copy className="w-4 h-4" />
                                Markdown 복사
                            </Button>
                            {isAuthenticated && (
                                <Button
                                    onClick={handleDelete}
                                    variant="danger"
                                    isLoading={deleteMutation.isPending}
                                    className="flex items-center gap-2 px-4 py-2 rounded-lg font-semibold bg-red-600 hover:bg-red-700 text-white"
                                    title="회고 삭제 (본인이 작성한 회고만 삭제 가능)"
                                >
                                    <Trash2 className="w-4 h-4" />
                                    삭제
                                </Button>
                            )}
                        </div>

                        <div className="prose dark:prose-invert max-w-none prose-headings:font-bold prose-h1:text-3xl prose-h2:text-2xl prose-h3:text-xl prose-code:bg-gray-100 dark:prose-code:bg-gray-800 prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-pre:bg-gray-900 dark:prose-pre:bg-gray-950 prose-pre:text-gray-100">
                            <ReactMarkdown 
                                remarkPlugins={[remarkGfm]}
                                components={{
                                    code: ({ node, inline, className, children, ...props }: any) => {
                                        const match = /language-(\w+)/.exec(className || '');
                                        return !inline && match ? (
                                            <pre className="bg-gray-900 dark:bg-gray-950 text-gray-100 p-4 rounded-lg overflow-x-auto my-4">
                                                <code className={className} {...props}>
                                                    {children}
                                                </code>
                                            </pre>
                                        ) : (
                                            <code className="bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 rounded text-sm" {...props}>
                                                {children}
                                            </code>
                                        );
                                    },
                                }}
                            >
                                {retrospective.content}
                            </ReactMarkdown>
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    );
};

