import { describe, expect, it } from 'vitest';
import type { TemplateSummary } from '../../../types/api/template.types';
import {
    ensureTemplateDefaultSections,
    selectTemplateForRetrospective,
} from './templateFlow';

const createTemplate = (overrides: Partial<TemplateSummary>): TemplateSummary => ({
    id: 'tpl',
    studentId: null,
    title: 'template',
    type: 'CUSTOM',
    isDefaultSuccess: false,
    isDefaultFail: false,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    ...overrides,
});

describe('templateFlow', () => {
    it('기본 템플릿 선택은 카테고리 기본값을 최우선으로 사용한다', () => {
        const templates: TemplateSummary[] = [
            createTemplate({ id: 'sys', type: 'SYSTEM' }),
            createTemplate({ id: 'custom-success', isDefaultSuccess: true }),
        ];

        const selected = selectTemplateForRetrospective(templates, 'SUCCESS');
        expect(selected?.id).toBe('custom-success');
    });

    it('카테고리 기본값이 없으면 SYSTEM 템플릿을 fallback으로 사용한다', () => {
        const templates: TemplateSummary[] = [
            createTemplate({ id: 'custom-1', type: 'CUSTOM' }),
            createTemplate({ id: 'system-1', type: 'SYSTEM' }),
        ];

        const selected = selectTemplateForRetrospective(templates, 'FAIL');
        expect(selected?.id).toBe('system-1');
    });

    it('기본 섹션 보정은 기존 본문을 유지하고 누락된 섹션만 추가한다', () => {
        const input = [
            '# 내 커스텀 제목',
            '',
            '## 접근 방법',
            '',
            '투 포인터로 풀이',
        ].join('\n');

        const result = ensureTemplateDefaultSections(input, '1000', 'Silver 1');

        expect(result).toContain('# 내 커스텀 제목');
        expect(result).toContain('## 접근 방법');
        expect(result).toContain('투 포인터로 풀이');
        expect(result).toContain('## 제출한 코드');
        expect(result).toContain('[문제 링크](https://www.acmicpc.net/problem/1000) | 티어: Silver 1');
        expect(result).toContain('Generated by DidimLog');
    });
});
